<?php

namespace App;

use App\Scopes\ActiveScope;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','weixin','qq', 'phone','group_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function hospitals()
    {
        return $this->belongsToMany('App\Models\Hospital');
    }


    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ActiveScope());
    }

}
