<?php

namespace App\Models;

use App\Scopes\HospitalScope;
use Illuminate\Database\Eloquent\Model;

class AppointmentTrack extends Model
{
    protected $fillable = ['next','hospital_id', 'user_id', 'appointment_id', 'content'];

    protected $dates = [
        'updated_at',
        'created_at',
        'next'
    ];


    public function user()
    {
        return $this->belongsTo('App\User');
    }


    public function appointment()
    {
        return $this->belongsTo('App\Models\Appointment');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new HospitalScope());
    }
}
