<?php

namespace App\Models;

use App\Scopes\HospitalScope;
use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    protected $fillable = [
        'name',
        'phone',
        'gender',
        'age',
        'doctor_id',
        'illness_id',
        'hospital_id',
        'user_id',
        'way_id',
        'province',
        'city',
        'town',
        'address',
        'book_date',
        'content',
        'qq',
        'job',
        'app_num'
    ];

    protected  $dates = [
        'book_date',
        'updated_at',
        'created_at',
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new HospitalScope());
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function illness()
    {
        return $this->belongsTo('App\Models\Illness');
    }


//    public function way()
//    {
//        return $this->belongsTo('way');
//    }


    public function tracks()
    {
        return $this->hasMany('App\Models\AppointmentTrack');
    }
}
