<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Model;

class Hospital extends Model
{

    protected $fillable = ['name', 'active', 'sort'];

    public function users()
    {
        return $this->belongsToMany('App\User');
    }



    public function illnesses()
    {
        return $this->hasMany('App\Models\Illness');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ActiveScope());
    }
}
