<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use App\Scopes\HospitalScope;
use Illuminate\Database\Eloquent\Model;

class Illness extends Model
{

    public $timestamps = false;

    protected  $fillable = ['name', 'sort', 'active', 'hospital_id'];





    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new HospitalScope());
        static::addGlobalScope(new ActiveScope());
    }

}
