<?php

namespace App\Models;

use App\Scopes\HospitalScope;
use Illuminate\Database\Eloquent\Model;

class Ways extends Model
{
    public $timestamps = false;

    protected  $fillable = ['name', 'hospital_id', 'active', 'sort'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new HospitalScope());
    }

}
